
name: second-job
on:
  push:
    branches:
      - main
jobs:

deploy:
  runs-on: ubuntu-latest
  if: ${{ always() }}
  needs: [setup]
    -
      name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: johnk777docker
        password: sera777docker
        #username: ${{secrets.DOCKER_UN}}
        #password: ${{secrets.DOCKER_PW}}

    - name: Push to Dockerhub
      run: |
        docker tag github-cicd-dc_github-cicd-dc-app johnk777docker/github-cicd-dc_github-cicd-dc-app
        docker push johnk777docker/github-cicd-dc_github-cicd-dc-app